### ISSUE TITLE
Membership Leaderboard, Network Allocations UI

### ISSUE THREAD

**Issue by 1kevinxu1** [Default-DAO/default-frontend#1]
I think it would be great to have a page that's just a leaderboard of all the members in the network and the net tokens they have, as a % of the network. Maybe we get rid of this/make it less public after we get bigger, but for now I think it's really cool seeing where people are at in the network and could be a good way to incentivize people to get more involved when they see everyone who has ownership of the network.

On a similar topic, I really love seeing allocations in the network as well in the Google Sheets—part of this membership leaderboard could also be 2 more views: DNT staking allocations, and $CLOUT allocations. Every week after we lock things in we can publish a sheet that shows how everyone delegated/allocated in a single view.

**Comment by scottsgcho** [comment]
This is definitely a good idea. I was thinking we might want an experience similar to that of the spreadsheet as well. I'll get on this soon.
